server:
  port: 8081

spring:
  application:
    name: opcua-client
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/opcua
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
    hikari:
      data-source-properties:
        stringtype: unspecified
        client_encoding: UTF8

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    encoding: UTF-8
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      max-retry-attempts: 5
      retry-delay: 1000
      properties:
        max:
          in:
            flight:
              requests:
                per:
                  connection: 1
    topic:
      opcua-data: opcua-data-collection

logging:
  level:
    root: INFO
    com.example.opcua: DEBUG